name: wavenet
description: A simple wrapper for accessing Google's Text-To-Spech API and converting the results to MP3 files.
version: 2.0.2
homepage: https://github.com/jonafeucht/Flutter-WaveNet-API
repository: https://github.com/jonafeucht/Flutter-WaveNet-API

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.13.3 <1.0.0"
  path_provider: ">=2.0.2 <3.0.0"
  dart_vlc: ">=0.0.9 <1.0.0"
  universal_platform: ">=1.0.0+1 <2.0.0"

flutter:
